<?php

use Illuminate\Database\Seeder;

class MdmCustomerProfileWebTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::connection('mysql')->table('mdm_customer_profile_web')->delete();
        
        \DB::connection('mysql')->table('mdm_customer_profile_web')->insert(array (
            0 => 
            array (
                'u_id' => '0000002A-0F96-4E03-903D-9FC0D37E0280',
                'uid_golden' => 'TE19691408',
                'unit' => 'INSU',
                'customer_id' => 'IFL00053191',
                'full_name' => 'FTV',
                'first_name' => 'FTV',
                'middle_name' => NULL,
                'last_name' => NULL,
                'surname' => NULL,
                'nickname' => NULL,
                'gender' => '1',
                'dob' => '1982-07-25',
                'pob_id' => NULL,
                'address' => 'JL. AMBAR BINANGUN NO. 469 RT. 11 (FOTOCOPY MERRY)',
                'nomor' => NULL,
                'blok' => NULL,
                'rt' => NULL,
                'rw' => NULL,
                'kelurahan_id' => NULL,
                'kecamatan_id' => NULL,
                'kota_id' => NULL,
                'propinsi_id' => NULL,
                'kodepos' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'status_tempat_tinggal_id' => NULL,
                'type_tempat_tinggal_id' => NULL,
                'category_tempat_tinggal_id' => NULL,
                'email1' => 'random@gmail.com',
                'email2' => NULL,
                'telepon_rumah' => NULL,
                'telepon_kantor' => NULL,
                'fax' => NULL,
                'mobile_phone1' => NULL,
                'mobile_phone2' => NULL,
                'ktp' => NULL,
                'category_identity_id' => 68,
                'suku_id' => NULL,
                'kewarganegaraan_id' => NULL,
                'negara_id' => NULL,
                'religion_id' => NULL,
                'pendidikan_id' => NULL,
                'profesi_id' => NULL,
                'golongan_darah_id' => NULL,
                'status_kawin_id' => NULL,
                'mortalitas_id' => NULL,
                'status_keaktifan_id' => NULL,
                'status_pengkinian_data_id' => NULL,
                'category_user_id' => NULL,
                'foto' => NULL,
                'golden' => NULL,
                'flag_process' => NULL,
                'process_at' => '2020-06-22 10:18:07.013689',
                'created_by' => 1,
                'created_at' => NULL,
                'updated_by' => NULL,
                'updated_at' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'id' => 13202298,
                'flag_mask' => 0,
                'batch' => '20200620100648',
                'status_ktp' => NULL,
                'title_pre' => NULL,
                'title_suf' => NULL,
                'jabatan' => NULL,
            ),
            1 => 
            array (
                'u_id' => '00000348-C9F8-42AB-87E0-7AA031C35680',
                'uid_golden' => 'TE19691408',
                'unit' => 'INSU',
                'customer_id' => '730358217',
                'full_name' => 'SARYOTO .',
                'first_name' => 'SARYOTO .',
                'middle_name' => NULL,
                'last_name' => NULL,
                'surname' => NULL,
                'nickname' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pob_id' => NULL,
                'address' => NULL,
                'nomor' => NULL,
                'blok' => NULL,
                'rt' => NULL,
                'rw' => NULL,
                'kelurahan_id' => NULL,
                'kecamatan_id' => NULL,
                'kota_id' => NULL,
                'propinsi_id' => NULL,
                'kodepos' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'status_tempat_tinggal_id' => NULL,
                'type_tempat_tinggal_id' => NULL,
                'category_tempat_tinggal_id' => NULL,
                'email1' => NULL,
                'email2' => NULL,
                'telepon_rumah' => '0812',
                'telepon_kantor' => NULL,
                'fax' => NULL,
                'mobile_phone1' => '0812',
                'mobile_phone2' => NULL,
                'ktp' => NULL,
                'category_identity_id' => NULL,
                'suku_id' => NULL,
                'kewarganegaraan_id' => NULL,
                'negara_id' => NULL,
                'religion_id' => NULL,
                'pendidikan_id' => NULL,
                'profesi_id' => NULL,
                'golongan_darah_id' => NULL,
                'status_kawin_id' => NULL,
                'mortalitas_id' => NULL,
                'status_keaktifan_id' => NULL,
                'status_pengkinian_data_id' => NULL,
                'category_user_id' => NULL,
                'foto' => NULL,
                'golden' => 'Y',
                'flag_process' => NULL,
                'process_at' => '2020-06-22 10:18:07.013689',
                'created_by' => 1,
                'created_at' => NULL,
                'updated_by' => NULL,
                'updated_at' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'id' => 13202300,
                'flag_mask' => 0,
                'batch' => '20200620100648',
                'status_ktp' => NULL,
                'title_pre' => NULL,
                'title_suf' => NULL,
                'jabatan' => NULL,
            ),
            2 => 
            array (
                'u_id' => '00000373-7055-4101-A6F2-469BBB10805D',
                'uid_golden' => 'TE11212045',
                'unit' => 'FINA',
                'customer_id' => '710271381',
                'full_name' => 'VINCENT',
                'first_name' => 'VINCENT',
                'middle_name' => NULL,
                'last_name' => NULL,
                'surname' => NULL,
                'nickname' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pob_id' => NULL,
                'address' => NULL,
                'nomor' => NULL,
                'blok' => NULL,
                'rt' => NULL,
                'rw' => NULL,
                'kelurahan_id' => NULL,
                'kecamatan_id' => NULL,
                'kota_id' => NULL,
                'propinsi_id' => NULL,
                'kodepos' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'status_tempat_tinggal_id' => NULL,
                'type_tempat_tinggal_id' => NULL,
                'category_tempat_tinggal_id' => NULL,
                'email1' => NULL,
                'email2' => NULL,
                'telepon_rumah' => '0812',
                'telepon_kantor' => NULL,
                'fax' => NULL,
                'mobile_phone1' => '0812',
                'mobile_phone2' => NULL,
                'ktp' => NULL,
                'category_identity_id' => NULL,
                'suku_id' => NULL,
                'kewarganegaraan_id' => NULL,
                'negara_id' => NULL,
                'religion_id' => NULL,
                'pendidikan_id' => NULL,
                'profesi_id' => NULL,
                'golongan_darah_id' => NULL,
                'status_kawin_id' => NULL,
                'mortalitas_id' => NULL,
                'status_keaktifan_id' => NULL,
                'status_pengkinian_data_id' => NULL,
                'category_user_id' => NULL,
                'foto' => NULL,
                'golden' => 'Y',
                'flag_process' => NULL,
                'process_at' => '2020-06-22 10:18:07.013689',
                'created_by' => 1,
                'created_at' => NULL,
                'updated_by' => NULL,
                'updated_at' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'id' => 13202301,
                'flag_mask' => 0,
                'batch' => '20200620100648',
                'status_ktp' => NULL,
                'title_pre' => NULL,
                'title_suf' => NULL,
                'jabatan' => NULL,
            ),
            3 => 
            array (
                'u_id' => '00000519-9DB4-4129-B1BA-807BA999FC1D',
                'uid_golden' => 'TE11212045',
                'unit' => 'FINA',
                'customer_id' => '410082318',
                'full_name' => 'Winda',
                'first_name' => 'Winda',
                'middle_name' => NULL,
                'last_name' => NULL,
                'surname' => NULL,
                'nickname' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pob_id' => NULL,
                'address' => 'JL. JEND. SUDIRMAN 11 ATAMBUA',
                'nomor' => NULL,
                'blok' => NULL,
                'rt' => NULL,
                'rw' => NULL,
                'kelurahan_id' => NULL,
                'kecamatan_id' => NULL,
                'kota_id' => NULL,
                'propinsi_id' => '53',
                'kodepos' => '11111     ',
                'longitude' => NULL,
                'latitude' => NULL,
                'status_tempat_tinggal_id' => NULL,
                'type_tempat_tinggal_id' => NULL,
                'category_tempat_tinggal_id' => NULL,
                'email1' => 'random@yahoo.co.id',
                'email2' => NULL,
                'telepon_rumah' => NULL,
                'telepon_kantor' => NULL,
                'fax' => NULL,
                'mobile_phone1' => NULL,
                'mobile_phone2' => NULL,
                'ktp' => NULL,
                'category_identity_id' => NULL,
                'suku_id' => NULL,
                'kewarganegaraan_id' => NULL,
                'negara_id' => 10,
                'religion_id' => NULL,
                'pendidikan_id' => NULL,
                'profesi_id' => NULL,
                'golongan_darah_id' => NULL,
                'status_kawin_id' => NULL,
                'mortalitas_id' => NULL,
                'status_keaktifan_id' => NULL,
                'status_pengkinian_data_id' => NULL,
                'category_user_id' => NULL,
                'foto' => NULL,
                'golden' => NULL,
                'flag_process' => NULL,
                'process_at' => '2020-06-22 10:18:07.013689',
                'created_by' => 1,
                'created_at' => NULL,
                'updated_by' => NULL,
                'updated_at' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'id' => 13202302,
                'flag_mask' => 0,
                'batch' => '20200620100648',
                'status_ktp' => NULL,
                'title_pre' => NULL,
                'title_suf' => NULL,
                'jabatan' => NULL,
            ),
        ));
        
        
    }
}