<?php

use Illuminate\Database\Seeder;

class MdmMstCompanyTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::connection('mysql')->table('mdm_mst_company')->delete();
        
        \DB::connection('mysql')->table('mdm_mst_company')->insert(array (
            0 => 
            array (
                'id' => 'SPIN',
            'full_name' => 'PT MNC Tekonologi Nusantara (MTN)',
                'isholding' => 'N',
                'address' => 'MNC Financial Center, 11th Floor, Jl. Kebon Sirih No. 21-27, Jakarta 10340, Indonesia',
                'website' => 'https://www.spinpay.id',
                'oracle_code' => 0,
                'brand_name' => 'SPIN',
                'email' => 'cs@spinpay.id',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_mtn_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            1 => 
            array (
                'id' => 'ALDN',
                'full_name' => 'Mister Aladin',
                'isholding' => 'N',
                'address' => NULL,
                'website' => NULL,
                'oracle_code' => NULL,
                'brand_name' => 'Mister Aladin',
                'email' => NULL,
                'holding' => NULL,
                'db_schema' => 'mdm_staging_aladin',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => 'Willian Reinhard Marpaung',
                'pic1_email' => NULL,
                'pic1_hp' => '0812-9891-5853',
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            2 => 
            array (
                'id' => 'ROOV',
                'full_name' => 'Roov Radio',
                'isholding' => 'N',
                'address' => '',
                'website' => 'https://www.roov.id',
                'oracle_code' => 0,
                'brand_name' => 'Roov',
                'email' => '',
                'holding' => '',
                'db_schema' => 'mdm_staging_roov_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            3 => 
            array (
                'id' => 'MKAP',
                'full_name' => 'PT MNC Kapital Indonesia Tbk',
                'isholding' => 'Y',
                'address' => 'MNC Financial Center 21st Floor, Jl. Kebon Sirih No 21-27, Jakarta Pusat 10340, Indonesia',
                'website' => 'https://www.mncgroup.com/microsite/mnc-financial-services',
                'oracle_code' => 0,
                'brand_name' => 'MNC Kapital',
                'email' => 'corsec.mncfinancialservices@mncgroup.com',
                'holding' => NULL,
                'db_schema' => NULL,
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            4 => 
            array (
                'id' => 'TEST',
                'full_name' => 'Test Case Business Unit',
                'isholding' => 'N',
                'address' => NULL,
                'website' => NULL,
                'oracle_code' => NULL,
                'brand_name' => NULL,
                'email' => NULL,
                'holding' => NULL,
                'db_schema' => NULL,
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            5 => 
            array (
                'id' => 'ASET',
                'full_name' => 'PT MNC Asset Management',
                'isholding' => 'N',
                'address' => 'MNC Financial Center, Lt. 9, Jl. Kebon Sirih No. 21-27, Jakarta 10340',
                'website' => 'https://www.mncasset.com',
                'oracle_code' => 0,
                'brand_name' => 'MNC Asset Management',
                'email' => '',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_assetmgt_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            6 => 
            array (
                'id' => 'BANK',
                'full_name' => 'PT Bank MNC Internasional Tbk',
                'isholding' => 'N',
                'address' => 'Gedung MNC Financial Center Lantai 6, 7, 8, Jl. Kebon Sirih Raya No. 27, Jakarta Pusat 10340',
                'website' => 'https://mncbank.co.id',
                'oracle_code' => 0,
                'brand_name' => 'MNC Bank',
                'email' => '',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_bank_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            7 => 
            array (
                'id' => 'MVN',
                'full_name' => 'PT MNC Vision Networks Tbk',
                'isholding' => 'Y',
                'address' => 'PT MNC Vision Networks Tbk, MNC Tower, 27/F, MNC Center, Jl. Kebon Sirih Kav. 17 – 19, Jakarta Pusat 10340 - Indonesia',
                'website' => 'https://www.mncgroup.com/microcontact/mnc-vision-networks',
                'oracle_code' => 0,
                'brand_name' => 'MNC Vision Networks',
                'email' => 'investor.mvn@mncgroup.com',
                'holding' => NULL,
                'db_schema' => NULL,
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            8 => 
            array (
                'id' => 'STAR',
            'full_name' => 'PT. Star Media Nusantara (SMN)',
                'isholding' => 'N',
                'address' => 'MNC STUDIOS - Tower II Lt.2, Jl. Raya Perjuangan no.1, Kebon Jeruk, Jakarta Barat 11530, Indonesia',
                'website' => 'https://www.starmedianusantara.com',
                'oracle_code' => 0,
                'brand_name' => 'SMN',
                'email' => 'info.smn@mncgroup.com',
                'holding' => '',
                'db_schema' => 'mdm_staging_smn_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            9 => 
            array (
                'id' => 'SNDO',
                'full_name' => 'Sindo',
                'isholding' => 'N',
                'address' => '',
                'website' => 'https://www.sindonews.com',
                'oracle_code' => 0,
                'brand_name' => 'Sindo',
                'email' => '',
                'holding' => '',
                'db_schema' => 'mdm_staging_sindo_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            10 => 
            array (
                'id' => 'MNIE',
            'full_name' => 'PT. MNI Entertainment (MNIE)',
                'isholding' => 'N',
                'address' => '',
                'website' => 'http://www.highend-magazine.com',
                'oracle_code' => 0,
                'brand_name' => 'MNI Entertainment',
                'email' => '',
                'holding' => '',
                'db_schema' => 'mdm_staging_mnie_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            11 => 
            array (
                'id' => 'MNCA',
                'full_name' => 'MNC Animation',
                'isholding' => 'N',
            'address' => 'MNC Studios, Tower 2 (RCTI) - 7th Floor Jln Raya Perjuangan No 1, Kebon jeruk RT.11/RW.10 Jakarta Barat 11530',
                'website' => 'https://www.mncanimation.com',
                'oracle_code' => 0,
                'brand_name' => 'MNC Animation',
                'email' => 'admin.mnca@mncgroup.com',
                'holding' => '',
                'db_schema' => 'mdm_staging_mnca_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            12 => 
            array (
                'id' => 'MCON',
                'full_name' => 'MNC Contents / Licensing',
                'isholding' => 'N',
                'address' => 'MNC News Center Building, 5th floor, Jalan K.H. Wahid Hasyim No.28, Jakarta – 10340, Indonesia',
                'website' => 'https://www.mnccontents.com',
                'oracle_code' => 0,
                'brand_name' => 'MNC Contents',
                'email' => '',
                'holding' => '',
                'db_schema' => 'mdm_staging_mnccontents_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            13 => 
            array (
                'id' => 'INFO',
            'full_name' => 'MNC Infotainment Indonesia (MII)',
                'isholding' => 'N',
                'address' => 'MNC Studios, Tower II, Jl. Raya Perjuangan, Kebon Jeruk, Jakarta 11350, Indonesia',
                'website' => 'https://www.mncchannels.com/micro/infotainment',
                'oracle_code' => 0,
                'brand_name' => 'MII',
                'email' => '',
                'holding' => '',
                'db_schema' => 'mdm_staging_mii_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            14 => 
            array (
                'id' => 'OKEZ',
                'full_name' => 'Okezone',
                'isholding' => 'N',
                'address' => 'iNews TV Building, 12th floor. Jln. KH.Wahid Hasyim No. 36-38, Jakarta 10350',
                'website' => 'https://www.okezone.com',
                'oracle_code' => 0,
                'brand_name' => 'Okezone',
                'email' => 'redaksi.okezone@mncgroup.com',
                'holding' => '',
                'db_schema' => 'mdm_staging_okezone_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            15 => 
            array (
                'id' => 'MRAD',
                'full_name' => 'MNCN Radio',
                'isholding' => 'N',
                'address' => 'MNC NEWS CENTER Lt. 5',
                'website' => 'https://www.mncnetworks.com',
                'oracle_code' => 0,
                'brand_name' => 'MNCN Radio',
                'email' => 'info@mncnetworks.com',
                'holding' => '',
                'db_schema' => 'mdm_staging_mncn_dev',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => NULL,
                'tbl_profile' => NULL,
                'last_clean_job' => NULL,
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            16 => 
            array (
                'id' => 'VPLS',
                'full_name' => 'PT MNC OTT Network',
                'isholding' => 'N',
                'address' => 'iNews Tower, Lantai 10, Jl. Kebon Sirih No. 17-19',
                'website' => 'https://www.visionplus.id',
                'oracle_code' => 0,
                'brand_name' => 'Vision+',
                'email' => 'ccare@visionplus.id',
                'holding' => 'MVN',
                'db_schema' => 'mdm_staging_vplus',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_vplus.mdm_staging_customer_profile',
                'last_clean_job' => '2020-07-16 00:00:00',
                'last_update' => NULL,
                'pic1_name' => 'Anggoro Primadi Mahardika',
                'pic1_email' => 'anggoro.mahardika@mncgroup.com',
                'pic1_hp' => '0888-8312-244',
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            17 => 
            array (
                'id' => 'MSSO',
                'full_name' => 'MNC Digital Single-Sign-On',
                'isholding' => 'N',
                'address' => 'iNews Tower, Lantai 2, Jl. Kebon Sirih Kav 17-19',
                'website' => 'https://account.mncdigital.id',
                'oracle_code' => 0,
                'brand_name' => 'MNC Digital SSO',
                'email' => 'jimmy.basselo@mncgroup.com',
                'holding' => 'MNC',
                'db_schema' => 'mdm_staging_sso',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_sso.mdm_staging_customer_profile',
                'last_clean_job' => '2018-01-11 01:00:00',
                'last_update' => NULL,
                'pic1_name' => 'Jimmy Basselo',
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            18 => 
            array (
                'id' => 'TFTH',
            'full_name' => 'PT. NUSANTARA SARANA OUTLET (THE F THING)',
                'isholding' => 'N',
                'address' => 'INEWS CENTER 12TH FLOOR, MNC CENTER COMPLEX, JL. KEBON SIRIH NO. 17-19, JAKARTA PUSAT 10340, DKI JAKARTA, INDONESIA',
                'website' => 'https://thefthing.com',
                'oracle_code' => 0,
                'brand_name' => 'The F-Thing',
                'email' => 'cs@thefthing.com',
                'holding' => '',
                'db_schema' => 'mdm_staging_tft',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_tft.mdm_staging_customer_profile',
                'last_clean_job' => '2018-01-11 01:00:00',
                'last_update' => NULL,
                'pic1_name' => 'Niken',
                'pic1_email' => NULL,
                'pic1_hp' => '0818-0301-0008',
                'pic2_name' => 'Eugene',
                'pic2_email' => NULL,
                'pic2_hp' => '0896-6973-6203',
            ),
            19 => 
            array (
                'id' => 'RPLS',
                'full_name' => 'RCTI+',
                'isholding' => 'N',
                'address' => '',
                'website' => 'https://www.rctiplus.com',
                'oracle_code' => 0,
                'brand_name' => 'RCTI+',
                'email' => '',
                'holding' => '',
                'db_schema' => 'mdm_staging_rplus',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_rplus.mdm_staging_customer_profile',
                'last_clean_job' => '2018-01-11 01:00:00',
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            20 => 
            array (
                'id' => 'LIFE',
                'full_name' => 'PT MNC Life Assurance',
                'isholding' => 'N',
                'address' => 'MNC Financial Center, 18th Floor, Jl. Kebon Sirih No. 21-27, Jakarta 10340, Indonesia',
                'website' => 'https://www.mnclife.com',
                'oracle_code' => 0,
                'brand_name' => 'MNC Life',
                'email' => 'customer@mnclife.com',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_life',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_life.mdm_staging_customer_profile_new',
                'last_clean_job' => '2020-07-16 00:00:00',
                'last_update' => '2019-05-20 13:22:00',
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            21 => 
            array (
                'id' => 'SEKU',
                'full_name' => 'PT MNC Sekuritas',
                'isholding' => 'N',
                'address' => 'PT MNC Sekuritas, MNC Financial Center Lt. 15-16, Jl. Kebon Sirih No.21-27, Jakarta Pusat 10340',
                'website' => 'https://www.mncsekuritas.id',
                'oracle_code' => 0,
                'brand_name' => 'MNC Sekuritas',
                'email' => 'callcenter.mncs@mncgroup.com',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_sekuritas',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_sekuritas.mdm_staging_customer_profile_new',
                'last_clean_job' => '2020-07-16 00:00:00',
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            22 => 
            array (
                'id' => 'KVIS',
                'full_name' => 'PT. Digital Vision Nusantara',
                'isholding' => 'N',
                'address' => 'Gedung The Jakarta Post, Lantai 4, Jl. Palmerah Barat No. 142-143 Jakarta Pusat, DKI Jakarta, Kode Pos: 10270',
                'website' => 'https://www.k-vision.tv',
                'oracle_code' => 0,
                'brand_name' => 'KVision',
                'email' => 'cs@k-vision.tv',
                'holding' => 'MVN',
                'db_schema' => 'mdm_staging_kvision',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_kvision.mdm_staging_customer_profile',
                'last_clean_job' => '2020-07-07 00:49:08',
                'last_update' => NULL,
                'pic1_name' => 'Ferry Aryanto',
                'pic1_email' => 'ferry.aryanto@k-vision.com',
                'pic1_hp' => NULL,
                'pic2_name' => 'Agung Wahyono',
                'pic2_email' => 'agung-wahyono@k-vision.tv',
                'pic2_hp' => '0812-2122-0516',
            ),
            23 => 
            array (
                'id' => 'PLAY',
            'full_name' => 'PT.MNC Kabel Mediacom (MKM)',
                'isholding' => 'N',
                'address' => 'MNC Tower, Lantai 10, 11, 12A, Jl. Kebon Sirih No. 17-19, Gondangdia, Jakarta Pusat',
                'website' => 'https://www.mncplay.id',
                'oracle_code' => 0,
                'brand_name' => 'MNC Play',
                'email' => 'ccare.mncplay@mncgroup.com',
                'holding' => 'MVN',
                'db_schema' => 'mdm_staging_play',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_play.mdm_staging_customer_profile',
                'last_clean_job' => '2018-01-11 01:00:00',
                'last_update' => NULL,
                'pic1_name' => 'Firdiansyah Firdaus Basri',
                'pic1_email' => 'firdiansyah.basri@mncgroup.com',
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            24 => 
            array (
                'id' => 'VISI',
                'full_name' => 'PT. MNC Sky Vision Tbk',
                'isholding' => 'N',
                'address' => 'MNC Vision Tower, Jl. Raya Panjang Z / III, Green Garden Jakarta 11520, Indonesia',
                'website' => 'https://www.mncvision.id',
                'oracle_code' => 0,
                'brand_name' => 'MNC Vision',
                'email' => 'ir.msky@mncgroup.com',
                'holding' => 'MVN',
                'db_schema' => 'mdm_staging_vision',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_vision.mdm_staging_customer_profile',
                'last_clean_job' => '2018-01-11 01:00:00',
                'last_update' => NULL,
                'pic1_name' => 'Merry Suryani',
                'pic1_email' => 'merry.suryani@mncgroup.com',
                'pic1_hp' => '0819-7667-500',
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            25 => 
            array (
                'id' => 'FINA',
                'full_name' => 'PT MNC Finance',
                'isholding' => 'N',
                'address' => 'MNC Financial Center lt. 12, Jl. Kebon Sirih No.21-27 Jakarta Pusat 10340',
                'website' => 'https://www.mncfinance.com',
                'oracle_code' => 0,
                'brand_name' => 'MNC Finance',
                'email' => 'customercare@mncfinance.com',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_finance',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_finance.mdm_staging_customer_profile_new',
                'last_clean_job' => '2020-07-16 00:00:00',
                'last_update' => '2019-06-11 11:23:00',
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            26 => 
            array (
                'id' => 'INSU',
                'full_name' => 'PT MNC Asuransi Indonesia',
                'isholding' => 'N',
                'address' => 'MNC Financial Center 11th Floor, Jl. Kebon Sirih no. 21 - 27, Jakarta Pusat 10340',
                'website' => 'https://www.mnc-insurance.com',
                'oracle_code' => 0,
                'brand_name' => 'MNC Insurance',
                'email' => 'info@mnc-insurance.com',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_insurance',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_insurance.mdm_staging_customer_profile_new',
                'last_clean_job' => '2020-07-16 00:00:00',
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
            27 => 
            array (
                'id' => 'LEAS',
                'full_name' => 'PT MNC Guna Usaha Indonesia',
                'isholding' => 'N',
                'address' => 'MNC Tower 23rd Floor Jl. Kebon Sirih No 17-19, Jakarta Pusat 10340 - Indonesia',
                'website' => 'https://www.mncleasing.com/',
                'oracle_code' => 0,
                'brand_name' => 'MNC Leasing',
                'email' => 'info.mncleasing@mncgroup.com',
                'holding' => 'MKAP',
                'db_schema' => 'mdm_staging_leasing',
                'db_user' => NULL,
                'db_passwd' => NULL,
                'masking_set' => NULL,
                'api_secret_key' => NULL,
                'clean_job' => 1,
                'tbl_profile' => 'mdm_staging_leasing.mdm_staging_customer_profile_new',
                'last_clean_job' => '2020-07-16 00:00:00',
                'last_update' => NULL,
                'pic1_name' => NULL,
                'pic1_email' => NULL,
                'pic1_hp' => NULL,
                'pic2_name' => NULL,
                'pic2_email' => NULL,
                'pic2_hp' => NULL,
            ),
        ));
        
        
    }
}